# pandas 시작하기

- pandas가 Numpy의 스타일을 많이 차용했지만, pandas는 **표 형식의 데이터나 다양한 형태의 데이터를 다루는 데** 초점을 맞춰 설계.


In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

> -  Series
> - DataFrame

In [4]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## 5.1.1 Series

- 일련의 객체를 담을 수 있는 1차원 배열 같은 자료구조다(어떤 Numpy 자료형이라도 담을 수 있다.)
- 색인(index)이라고 하는 배열의 데이터와 연관된 이름을 가지고 있다.


In [61]:
# 가장 간단한 Series 객체는 배열 데이터로부터 생성할 수 있다.
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

- Series의 배열과 색인 객체는 각각 values와 index 속성을 통해 얻을 수 있다.

In [62]:
obj.values

array([ 4,  7, -5,  3])

In [63]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [64]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [65]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [66]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

- 단일 값을 선택하거나 여러 값을 선택할 때 색인으로 라벨을 사용할 수 있다.

In [67]:
obj2['a']

-5

In [68]:
obj2['b']

7

In [69]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [70]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

- 불리언 배열을 사용해서 값을 걸러 내거나 산술 곱셈을 수행하거나 또는 수학 함수를 적용하는 등 Numpy 배열 연산을 수행해도 색인-값 연결이 유지된다.

In [71]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [72]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [73]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [74]:
'b' in obj2

True

In [75]:
'e' in obj2

False

- Series 객체는 파이썬의 사전형을 인자로 받아야 하는 많은 함수에서 사전형을 대체하여 사용할 수 있다.

In [76]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [77]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

- 'California'에 대한 값은 찾을 수 없기 때문에 NaN으로 표시.
- 'Utah'는 states에 포함되어 있지 않으므로 실행 결과에서 빠진다.


In [78]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [79]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [80]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

- Series의 유용한 기능은 산술 연산에서 색인과 라벨로 자동 정렬하는 것.

In [81]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [82]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [83]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [84]:
obj4.name = 'population'

In [85]:
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [86]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [87]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [88]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame



- DataFrame은 표 같은 스프레드시트 형식의 자료구조
- 여러 개의 컬럼이 있는데 각 컬럼은 서로 다른 종류의 값(숫자, 문자열, 불리언 등)을 담을 수 있다.
- 데이터는 하나 이상의 2차원 배열에 저장된다.

In [89]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [90]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

- DataFrame의 색인은 Series와 같은 방식으로 자동으로 대입되고 컬럼은 정렬되어 저장된다.

In [91]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [92]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [93]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [94]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [95]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [96]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

- frame[column]형태로 사용하는 것은 어떤 컬럼이든 가능하지만, frame2.column 형태로 사용하는 것은 파이썬에서 사용 가능한 변수 이름 형식일 때만 작동한다.

In [97]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [98]:
frame2['debt'] = 16.5

In [99]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [100]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [101]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [102]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [103]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [104]:
del frame2['eastern']

In [105]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [106]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [107]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [108]:
# NumPy 배열과 유사한 문법으로 데이터를 전치(컬럼과 로우를 뒤집음)할 수 있다.
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [109]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [110]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [111]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [112]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [113]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

- Series와 유사하게 values 속성은 DataFrame에 저장된 데이터를 2차원 배열로 반환.

> - 2차원 ndarray : 데이터를 담고 있는 행렬, 선택적으로 행(로우)과 열(컬럼)의 이름을 전달할 수 있다.

> - 배열, 리스트, 튜플의 사전 : 사전의 모든 항목은 같은 길이를 가져야 하며, 각 항목의 내용이 DataFrame의 컬럼이 된다.

> - NumPy의 구조화 배열 : 배열의 사전과 같은 방식으로 취급된다.

> - Series의 사전 : Series의 각 값이 컬럼이 된다. 명시적으로 색인을 넘겨주지 않으면 각 Series의 색인이 하나로 합쳐져서 로우의 색인이 된다.

> - 사전의 사전 : 내부에 있는 사전이 컬럼이 된다. 키 값은 'Series의 사전'과 마찬가지로 합쳐져서 로우의 색인이 된다.

> - 사전이나 Series의 리스트 : 리스트의 각 항목이 DataFrame의 로우가 된다. 합쳐진 사전의 키값이나 Series의 색인이 DataFrame의 컬럼 이름이 된다.

> - 리스트나 튜플의 리스트 : '2차원 ndarray'의 경우와 같은 방식으로 취급된다.

> - 다른 DataFrame : 색인을 따로 지정하지 않으면 DataFrame의 색인이 그대로 사용된다.

> - NumPy MaskedArray : '2차원 ndarray'의 경우와 같은 방식으로 취급되지만 마스크값은 반환되는 DataFrame에서 NA 값이 된다.


## 5.1.3 색인 객체

In [114]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [115]:
index[1:]

Index(['b', 'c'], dtype='object')

In [116]:
index[1] = 'd' # TypeError
# 색인 객체는 변경이 불가능하다.

TypeError: Index does not support mutable operations

In [117]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [118]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [119]:
obj2.index is labels

True

In [120]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [121]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [122]:
'Ohio' in frame3.columns

True

In [123]:
2003 in frame3.index

False

In [124]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### 색인 메서드와 속성

> -  append : 추가적인 색인 객체를 덧붙여 새로운 색인을 반환한다.

> -  difference : 색인의 차집합을 반환한다.

> -  intersection : 색인의 교집합을 반환한다.

> -  union : 색인의 합집합을 반환한다.

> -  isin : 색인이 넘겨받은 색인에 존재하는지 알려주는 불리언 배열을 반환한다.

> -  delete : i 위치의 색인이 삭제된 새로운 색인을 반환한다.

> -  drop : 넘겨받은 값이 삭제된 새로운 색인을 반환한다.

> -  insert : i 위치에 색인이 추가된 새로운 색인을 반환한다.

> -  is_monotonic : 색인이 단조성을 가진다면 True를 반환한다.

> -  is_unique : 중복되는 색인이 없다면 True를 반환한다.

> -  unique : 색인에서 중복되는 요소를 제거하고 유일한 값만 반환한다.

## 5.2 핵심기능



### 5.2.1 재색인

- reindex : 새로운 색인에 **맞도록** 객체를 새로 생성한다.


In [125]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [126]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

- 이 Series 객체에 대해 reindex를 호출하면 데이터를 새로운 색인에 맞게 재배열하고, 존재하지 않는 색인값이 있다면 NaN을 추가한다.

In [127]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [128]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

- method 옵션을 이용해서 시계열 같은 순차적인 데이터를 재색인할 때 값을 보간하거나 채워 넣을 수 있다.
- ffill 같은 메서드를 이용해서 누락된 값을 직전의 값으로 채워 넣을 수 있다.

In [129]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [130]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [131]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [170]:

frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

> - index : 색인으로 사용할 새로운 순서. Index 인스턴스나 다른 순차적인 자료구조가 사용 가능하다. Index는 복사가 이루어지지 않고 그대로 사용된다.
> - method : 채움 메서드, ffill은 직전 값을 채워 넣고 bfill은 다음 값을 채워 넣는다.
> - fill_value : 재색인 과정 중에 새롭게 나타나는 비어 있는 데이터를 채우기 위한 값
> - limit : 전/후 보간 시에 사용할 최대 갭 크기(채워넣을 원소의 수)
> - tolerance : 전/후 보간 시에 사용할 최대 갭 크기(값의 차이)
> - level : MultiIndex의 단계(level)에 단순 색인을 맞춘다. 그렇지 않으면 MultiIndex의 하위집합에 맞춘다.
> - copy : True인 경우 새로운 색인이 이전 색인과 동일하더라도 데이터를 복사한다. False인 경우 새로운 색인이 이전 색인과 동일할 경우 복사하지 않는다.

## 5.2.2 하나의 로우나 컬럼 삭제하기



In [151]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [152]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [153]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [154]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

- drop 함수에 인자로 로우 이름을 넘기면 해당 로우(axis 0)의 값을 모두 삭제한다.

In [161]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

- 컬럼의 값을 삭제할 때는 axis='columns'를 인자로 넘겨준다.

In [162]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [171]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## 5.2.3 색인하기, 선택하기, 거르기


- Series의 색인(obj[...])은 NumPy 배열의 색인과 유사하게 동작하지만 정수가 아니어도 된다.

In [172]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [173]:
obj['b']

1.0

In [174]:
obj[1]

1.0

In [175]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [176]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [177]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [178]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [179]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

- 라벨 이름으로 슬라이싱하면 시작점과 끝점을 포함한다는 것이 일반 파이썬에서의 슬라이싱과 다른 점이다.

In [180]:
obj['b':'c'] = 5
# 선택된 영역에 값을 대입

In [181]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [182]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [183]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [184]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [185]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [186]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [187]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [188]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### loc과 iloc으로 선택하기

- 축 이름을 선택할 때는 loc를, 정수 색인으로 선택할 때는 iloc를 사용한다.



In [189]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [190]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [191]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [192]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [193]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [194]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### DataFrame의 값 선택하기

> - df[val] : DataFrame에서 하나의 컬럼 또는 여러 컬럼을 선택한다. 편의를 위해 불리언 배열, 슬라이스, 불리언 DataFrame(이떤 기준에 근거해서 값을 대입해야 할 때)을 사용할 수 있다. 
> - df.loc[val] : DataFrame에서 라벨값으로 로우의 부분집합을 선택한다.
> - df.loc[:, val] : DataFrame에서 라벨값으로 컬럼의 부분집합을 선택한다.
> - df.loc[val1, val2] : DataFrame에서 라벨값으로 로우와 컬럼의 부분집합을 선택한다.
> - df.iloc[where] : DataFrame에서 정수 색인으로 로우의 부분집합을 선택한다. 
> - df.iloc[:, where] : DataFrame에서 정수 색인으로 컬럼의 부분집합을 선택한다.
> - df.iloc[where_i, wher_j] : DataFrame에서 정수 색인으로 로우와 컬럼의 부분집합을 선택한다.
> - df.at[label_i, label_j] : 로우와 컬럼의 라벨로 단일 값을 선택한다.
> - df.iat[i, j] : 로우와 컬럼의 정수 색인으로 단일 값을 선택한다.
> - reindex 메서드 : 하나 이상의 축을 새로운 색인으로 맞춘다.
> - get_vlaue, set_value 메서드 : 로우와 컬럼 이름으로 DataFrame의 값을 선택한다.


### 5.2.4 정수 색인



In [6]:
ser = pd.Series(np.arange(3.))
ser 

0    0.0
1    1.0
2    2.0
dtype: float64

In [7]:
ser[-1]

KeyError: -1

In [8]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [9]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [10]:
ser2[-1]

2.0

In [11]:
ser[:1]

0    0.0
dtype: float64

In [12]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [13]:
ser.iloc[:1]

0    0.0
dtype: float64

- 라벨에 대해서는 loc을 사용하고 정수 색인에 대해서는 iloc을 사용하자.

### 5.2.5 산술 연산과 데이터 정렬

- Pandas에서 가장 중요한 기능 중 하나는 다른 색인을 가지고 있는 객체 간의 산술 연산이다. 객체를 더할 때 짝이 맞지 않는 색인이 있다면 결과에 두 색인이 통합된다.

In [14]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [15]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [17]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [16]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

- 서로 겹치는 색인이 없는 경우 데이터는 NA 값이 된다.

In [18]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [19]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [20]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [21]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [22]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [23]:
df1

A
0  1
1  2

In [24]:
df2

B
0  3
1  4

In [25]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### 산술 연산 메서드에 채워 넣을 값 지정하기

- 서로 다른 색인을 가지는 객체 간의 산술 연산에서 존재하지 않는 축의 값을 특수한 값(0 같은)으로 지정하고 싶을 때는 다음과 같이 할 수 있다.



In [26]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [27]:
df2.loc[1, 'b'] = np.nan

In [28]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [29]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [30]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [31]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [33]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [34]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [35]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

> - add, radd : 덧셈(+)을 위한 메서드
> - sub, rsub : 뺄셈(-)을 위한 메서드
> - div, rdiv : 나눗셈(/)을 위한 메서드
> - floordiv, rfloordiv : 소수점 내림(//) 연산을 위한 메서드
> - mul, rmul : 곱셈(* )을 위한 메서드
> - pow, rpow : 멱승(** )을 위한 메서드

### DataFrame과 Series 간의 연산

In [36]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
arr[0]

array([0., 1., 2., 3.])

In [38]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

- arr에서 arr[0]을 빼면 계산은 각 로우에 대해 한 번씩만 수행된다. 이를 **브로드캐스팅**이라고 한다.

In [39]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [40]:
series = frame.iloc[0]

In [41]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [42]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [43]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [44]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [45]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [46]:
series3 = frame['d']

In [47]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [48]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [49]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

- 인자로 넘기는 axis 값은 **연산을 적용할 축 번호** axis = 'index'나 axis = 0은 DataFrame의 로우를 따라 연산을 수행하라는 의미다.

## 5.2.6 함수 적용과 매핑




In [50]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [51]:
np.abs(frame)

b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [52]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [53]:
frame.apply(f, axis='columns')

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

- axis를 columns으로 바꾸면 각 row에 대해 한번만 계산

In [54]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [55]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

- 배열의 각 원소에 적용되는 파이썬의 함수를 사용할 수도 있다. frame 객체에서 실숫값을 문자열 포맷으로 변환하고 싶다면 applymap을 이용.

In [56]:
frame['e'].map(format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

- Series는 각 원소에 적용할 함수를 지정하기 위한 map 메서드를 가지고 있다.

## 5.2.7 정렬과 순위



In [57]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [58]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [59]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [60]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [61]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [62]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

- 비어 있는 값은 마지막에 위치

In [63]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [67]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [66]:
frame.sort_values(by='a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [68]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [69]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

- 순위는 정렬과 거의 흡사, 1부터 배열의 유효한 데이터 개수까지 순서를 매긴다. 기본적으로 Series와 DataFrame의 rank 메서드는 동점인 항목에 대해서는 평균 순위를 매긴다.

In [70]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

- 먼저 출현한 순서대로 6과 7을 적용

In [71]:
# Assign tie values the maximum rank in the group
# 동률일 경우 그룹 내에서 높은 순위를 적용한다.
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [72]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [73]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

#### 순위의 동률을 처리하는 메서드
> - average : 기본값, 같은 값을 가지는 항목들의 평균값을 순위로 삼는다.
> - min : 같은 값을 가지는 그룹을 낮은 순위로 매긴다.
> - max : 같은 값을 가지는 그룹을 높은 순위로 매긴다.
> - first : 데이터 내의 위치에 따라 순위를 매긴다.
> - dense : method = 'min'과 같지만 같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가시킨다.



### 5.2.8 중복 색인


In [74]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [75]:
obj.index.is_unique

False

In [76]:
obj['a']

a    0
a    1
dtype: int64

In [77]:
obj['c']

4

In [78]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  0.274992  0.228913  1.352917
a  0.886429 -2.001637 -0.371843
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

In [79]:
df.loc['b']

0         1         2
b  1.669025 -0.438570 -0.539741
b  0.476985  3.248944 -1.021228

## 5.3 기술 통계 계산과 요약

- pandas 객체는 일반적인 수학 메서드의 통계 메서드를 가지고 있다.
- 하나의 Series나 DataFrame의 로우나 컬럼에서 단일 값(합이나 평균 같은)을 구하는 축소 혹은 요약 통계 범주에 속한다.

In [80]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [81]:


df.sum()



one    9.25
two   -5.80
dtype: float64

In [82]:


df.sum(axis='columns')



a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [83]:


df.mean(axis='columns', skipna=False)



a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

#### 축소 메서드의 옵션

> - axis : 연산을 수행할 축. DataFrame에서 0은 로우고 1은 컬럼이다.
> - skipna : 누락된 값을 제외할 것인지 정하는 옵션. 기본값은 True.
> - level : 계산하려는 축이 계층적 색인(다중 색인)이라면 레벨에 따라 묶어서 계산한다.

In [87]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [84]:
df.idxmax()

one    b
two    d
dtype: object

In [85]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [86]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [88]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

#### 요약 통계 관련 메서드


> - count : NA 값을 제외한 값의 수를 반환한다.
> - describe : Series나 DataFrame의 각 컬럼에 대한 요약 통계를 계산한다.
> - min, max : 최솟값과 최댓값을 계산한다.
> - argmin, argmax : 각각 최솟값과 최댓값을 담고 있는 색인의 위치(정수)를 반환한다.
> - idxmin, idxmax : 각각 최솟값과 최댓값을 담고 있는 색인의 값을 반환한다. 
> - quantile : 0부터 1까지의 분위수를 계산한다.
> - sum : 합을 계산한다.
> - mean : 평균을 계산한다.
> - median : 중간값(50% 분위)을 반환한다.
> - mad : 평균값에서 평균절대편차를 계산한다.
> - prod : 모든 값의 곱
> - var : 표본분산의 값을 계산한다.
> - std : 표본표준편차의 값을 계산한다.
> - skew : 표본비대칭도(3차 적률)의 값을 계산한다.
> - kurt : 표본첨도(4차 적률)의 값을 계산한다.
> - cumsum : 누적합을 계산한다.
> - cummin, cummax : 각각 누적 최솟값과 누적 최댓값을 계산한다. 
> - cumprod : 누적곱을 계산한다.
> - diff : 1차 산술차를 계산한다.(시계열 데이터 처리 시 유용하다.)
> - pct_change : 퍼센트 변화율을 계산한다.



### 5.3.1 상관 관계와 공분산

! conda install pandas-datareader

In [91]:


import pandas_datareader.data as web 
all_data = {ticker: web.get_data_yahoo(ticker) 
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close'] 
                      for ticker, data in all_data.items()}) 
volume = pd.DataFrame({ticker: data['Volume'] 
                       for ticker, data in all_data.items()})


In [93]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-12-29  0.000502  0.005429  0.002051  0.000386
2021-12-30 -0.006578  0.004199 -0.007691 -0.003427
2021-12-31 -0.003535 -0.001867 -0.008841 -0.009061
2022-01-03  0.025004  0.017806 -0.004668  0.002730
2022-01-04 -0.012692  0.014555 -0.017147 -0.004536

In [94]:
returns['MSFT'].corr(returns['IBM'])
# 연속하는 두 Series에 대해 상관관계를 계산

0.4961387055048709

In [95]:
returns['MSFT'].cov(returns['IBM'])
# 공분산을 계산

0.00014283811979406787

In [96]:
returns.MSFT.corr(returns.IBM)

0.4961387055048709

- MSFT는 파이썬 속성 이름 규칙에 어긋나지 않으므로 좀 더 편리한 문법으로 해당 컬럼을 선택 할 수 있다.

In [97]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.429966  0.736511  0.658935
IBM   0.429966  1.000000  0.496139  0.468574
MSFT  0.736511  0.496139  1.000000  0.778070
GOOG  0.658935  0.468574  0.778070  1.000000

In [98]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000369  0.000137  0.000245  0.000215
IBM   0.000137  0.000276  0.000143  0.000132
MSFT  0.000245  0.000143  0.000300  0.000229
GOOG  0.000215  0.000132  0.000229  0.000289

In [99]:
returns.corrwith(returns.IBM)

AAPL    0.429966
IBM     1.000000
MSFT    0.496139
GOOG    0.468574
dtype: float64

- DataFrame의 corrwith 메서드를 사용하면 다른 Series나 DataFrame과의 상관관계를 계산한다. Series를 넘기면 각 컬럼에 대해 계산한 상관관계를 담고 있는 Series를 반환한다.

In [100]:
returns.corrwith(volume)

AAPL   -0.073735
IBM    -0.134828
MSFT   -0.066805
GOOG   -0.111373
dtype: float64

- DataFrame을 넘기면 맞아떨어지는 컬럼 이름에 대한 상관관계를 계산한다. 
    - 여기서 시가총액의 퍼센트 변화율에 대한 상관관계를 계산.

## 5.3.2 유일값, 값 세기, 멤버십

In [101]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [102]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [103]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [104]:
pd.value_counts(obj.values, sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [105]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [106]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [107]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [108]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [109]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [110]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

> - isin : Series의 각 원소가 넘겨받은 연속된 값에 속하는지 나타내는 불리언 배열을 반환한다.
> - match : 각 값에 대해 유일한 값을 담고 있는 배열에서의 정수 색인을 계산한다. 데이터 정렬이나 조인 형태의 연산을 하는 경우에 유용하다.
> - unique : Series에서 중복되는 값을 제거하고 유일값만 포함하는 배열을 반환한다. 결과는 Series에서 발견된 순서대로 반환한다.
> - value_counts : Series에서 유일값에 대한 색인과 도수를 계산한다. 도수는 내림차순으로 정렬된다.

In [111]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [112]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

- 여기서 결괏값의 로우 라벨은 전체 컬럼의 유일한 값들을 담고 있다. 각 값은 각 컬럼에서 해당 값이 몇 번 출현했는지 나타낸다.

In [113]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS